#ifndef GOLD_SCALP_AI_ENUMS_MQH
#define GOLD_SCALP_AI_ENUMS_MQH

enum ENUM_GSA_LOG_LEVEL
  {
   GSA_LOG_ERROR = 0,
   GSA_LOG_WARNING,
   GSA_LOG_INFO,
   GSA_LOG_DEBUG
  };

enum ENUM_GSA_TRADE_DIRECTION
  {
   GSA_DIRECTION_NONE = 0,
   GSA_DIRECTION_BUY,
   GSA_DIRECTION_SELL
  };

enum ENUM_GSA_EA_STATE
  {
   GSA_STATE_INITIALIZING = 0,
   GSA_STATE_READY,
   GSA_STATE_PAUSED,
   GSA_STATE_ERROR
  };

#endif
